import Head from "next/head"
import Image from "next/image"
import { Inter } from "@next/font/google"
import styles from "../styles/Home.module.css"
import io from "socket.io-client"
import { useState } from "react"

const inter = Inter({ subsets: ["latin"] })

const socket = io("http://localhost:5000")

export default function Home() {
  const [message, setMessage] = useState("")
  const [list, setList] = useState<any>([])
  const handleSendMessage = () => {
    socket.emit("send_message", { message })
    setMessage("")
  }

  socket.on("received_message", (data) => {
    console.log(data)
    setList([...list, data])
  })
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <h2>チャットアプリ</h2>
        <div className={styles.chatInputButton}>
          <input
            type="text"
            placeholder="コメントを送信"
            onChange={(e) => setMessage(e.target.value)}
            value={message}
          />
          <button onClick={() => handleSendMessage()}>チャット送信</button>
          {list.map((chat: any) => (
            <div className={styles.chatArea} key={chat.message}>
              {chat.message}
            </div>
          ))}
        </div>
      </div>
    </>
  )
}
